version: "3.10"

services:
 db:
   image: postgres:13.3
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   environment:
     POSTGRES_DB: "habr_db"
     POSTGRES_USER: "habrpguser"
     POSTGRES_PASSWORD: "pgpwd4habr"
   ports:
     - "5435:5435"
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/shop
   ports:
     - "8000:8000"
   depends_on:
     - db
volumes:
  postgres_data:
