# Generated by Django 4.1.1 on 2022-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender1', models.EmailField(max_length=254, verbose_name='Type your emmail')),
                ('reciever', models.EmailField(max_length=254, verbose_name='Send to')),
            ],
        ),
    ]
