# Generated by Django 4.1.1 on 2022-09-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='reciever',
        ),
    ]
