# Generated by Django 4.1.1 on 2022-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0002_remove_sendemail_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
