# Generated by Django 4.1.1 on 2022-09-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_cart_product_cart_cart_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_products',
        ),
    ]
