# Generated by Django 4.1.1 on 2022-09-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_cart_alter_productlike_product_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='shop_app.product'),
        ),
    ]
